### ISSUE TITLE
[Suggestion] Update "The GUI can be found here" text in console

### ISSUE THREAD

**Issue by cyberofficial** [tunnels-is/tunnels#15]
Update "The GUI can be found here" text to say use "https://ip:port" rather just "ip:port"

Currently Text in console says this 
![image](https://github.com/user-attachments/assets/b60e55b5-bb45-4435-a53e-20bf7b8137d9)

The console should instruct users to visit "https://ip:port" as browsers will tend to default to http.

**Comment by zveinn** [comment]
Fixed on dev branch, will be in next release.. thanks !
